USE MOVIES;

--SELECT M.TITLE, E.NAME
--FROM MOVIE M JOIN MOVIEEXEC E
--ON M.PRODUCERC#=E.CERT#
--WHERE M.PRODUCERC# = (SELECT PRODUCERC#
--       FROM MOVIE
--	   WHERE TITLE = 'Star Wars')

--SELECT DISTINCT ME.NAME
--FROM MOVIEEXEC ME INNER JOIN MOVIE M
--ON ME.CERT# = M.PRODUCERC#
--JOIN STARSIN S
--ON M.TITLE = S.MOVIETITLE
--WHERE STARNAME = 'Harrison Ford'

--SELECT DISTINCT STUDIONAME, STARNAME
--FROM MOVIE JOIN STARSIN
--ON TITLE = MOVIETITLE


--SELECT STARNAME, NETWORTH, TITLE
--FROM MOVIEEXEC JOIN MOVIE
--ON CERT# = PRODUCERC#
--JOIN STARSIN ON TITLE = MOVIETITLE
--WHERE NETWORTH >= ALL(SELECT NETWORTH
--                      FROM MOVIEEXEC);

--SELECT M.NAME, S.MOVIETITLE
--FROM  STARSIN S RIGHT JOIN MOVIESTAR M
--ON S.STARNAME = M.NAME
--WHERE MOVIETITLE IS NULL;



USE PC;
--SELECT P.maker, P.model, P.type
--FROM PRODUCT P LEFT JOIN LAPTOP L
--ON P.MODEL = L.MODEL
--LEFT JOIN PRINTER PR
--ON P.MODEL = PR.MODEL
--LEFT JOIN PC C
--ON P.MODEL = C.MODEL
--WHERE L.MODEL IS NULL AND PR.MODEL IS NULL AND C.MODEL IS NULL;

--SELECT DISTINCT MAKER
--FROM PRODUCT P
--WHERE P.TYPE = 'Printer' AND P.MAKER IN (SELECT MAKER
--                                         FROM PRODUCT
--										 WHERE TYPE = 'Laptop')


--SELECT DISTINCT L.HD
--FROM LAPTOP L JOIN LAPTOP P
--ON L.HD = P.HD AND L.MODEL <> P.MODEL;

--SELECT PC.model
--FROM PC LEFT JOIN PRODUCT ON PC.model = PRODUCT.model
--WHERE PRODUCT.maker is NULL;
